export const GrassType = {
    SHADOW: 'SHADOW',
    SHADOW_HEIGHT: 'SHADOW_HEIGHT',
    SHADOW_SHORT: 'SHADOW_SHORT',
    LIGHT: 'LIGHT',
    LIGHT_HEIGHT: 'LIGHT_HEIGHT',
    LIGHT_RELIEF: 'LIGHT_RELIEF',
    LIGHT_STRAIGHT90: 'LIGHT_STRAIGHT90',
    LIGHT_STRAIGHT: 'LIGHT_STRAIGHT',
    CUTABLE_DRY: 'CUTABLE_DRY',
};

Object.freeze(GrassType);
